name: Vercel Action
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ x30jg6TuNwo2h0NRhPDQMUyd }} # Required
          vercel-project-id: ${{ prj_hAcKiqVPBT6MU41cPdCRWjAL74aJ }} 
